language: c
compiler:
  - gcc
  - clang

before_script:
  - wget http://googletest.googlecode.com/files/gtest-1.6.0.zip
  - unzip -q gtest-1.6.0.zip

script:
  - ./configure
  - make test

notifications:
  email:
    on_success: always
    on_failure: always