#
#  devenv Travis ci hook
#

language : c

compiler : 
	- gcc
	- clang

before_script :
	- wget http://googletest.googlecode.com/files/gtest-1.6.0.zip
	- unzip -q gtest-1.6.0.zip
	- cd gtest-1.6.0

script : ./configure && make && make test